### ISSUE TITLE
Support push notifications in IMAP

### ISSUE THREAD

**Issue by Akczht** [regnull/ubikom#45]
Push Notifications for IOS ?

**Comment by regnull** [comment]
Normally, specific email clients handle push notification. All we can do is to interact with them via IMAP. I suspect we can do a better support for push notifications in IMAP, because now the client needs to list all messages in a mailbox to find new messages. I believe there is a way to do it better. It's something to investigate.

**Comment by Akczht** [comment]
Thanks! For replying , I've contacted Ubikom on twitter also , So Please! ignore that . I'll be looking forward to Push Notifications . BTW I can tell you a way to get dirt cheap .in , .co.in , .net.in , .org.in , .gen.in , .firm.in . I'm talking 27$ for 10 Years and then we transfer them to Gandi.net or any good registrar .

**Comment by Akczht** [comment]
Just signup at mitsu.in and get the domain for 10 Years . And after 2 months of registration one can transfer off the domain .

**Comment by Akczht** [comment]
any progress ?

**Comment by regnull** [comment]
We don't have an ETA on this. Right now blockchain migration takes all the time and resources.

**Comment by Akczht** [comment]
got it
