### ISSUE TITLE
Add an alternative domain that is shorter than "ubikom"

### ISSUE THREAD

**Issue by Dyras** [regnull/ubikom#63]
Hello! Protonmail has "pm" as an alternative domain, available for all users. Would something similar be possible for Ubikom? It's quite a mouthful to spell out over the phone, for example.

**Comment by regnull** [comment]
It is definitely possible. Ubikom is domain-agnostic, and the only time the domain name comes into play is when we send and receive messages via the gateway. There could be multiple gateways. Anyone can configure and maintain a gateway, all you need is a domain name and some Linux knowledge. At this point, we don't want to create another domain ourselves because of added complexity and cost, but we can assist anyone who wants to operate a gateway. Also, you don't have to support all Ubikom users on your own gateway, you can restrict it to some subset of users.
